"""add user and transaction models

Revision ID: 6e4ae2863955
Revises: 
Create Date: 2025-10-11 00:03:24.104549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4ae2863955'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('daily_expense_limit', sa.Integer(), nullable=True),
    sa.Column('weekly_expense_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_expense_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('txn_mode', sa.Enum('Cash', 'Card', 'UPI', name='transaction_mode'), nullable=False),
    sa.Column('category', sa.Enum('Shopping', 'Food', 'Home', 'Transport', 'Health', 'Gifts', 'Savings', 'Salary', 'Other', name='transaction_category'), nullable=False),
    sa.Column('txn_type', sa.Enum('expense', 'income', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('users')
    # ### end Alembic commands ###
