"""add txn_date and comment column in txn model

Revision ID: 89d2f3d18de6
Revises: aa6aca804154
Create Date: 2025-10-16 19:30:24.431436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d2f3d18de6'
down_revision: Union[str, Sequence[str], None] = 'aa6aca804154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('txn_date', sa.DateTime(), nullable=False))
    op.add_column('transactions', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'comment')
    op.drop_column('transactions', 'txn_date')
    # ### end Alembic commands ###
